stages:
  - dependencies
  - Lint
  - Black

check_dependencies:
  stage: dependencies
  image: python:3.12
  before_script:
    - pip install --upgrade pip
  script:
    - pip install -r requirements/prod.txt
    - pip install -r requirements/dev.txt
    - pip install -r requirements/test.txt
  only:
    - main
    - merge_requests


flake8:
  stage: Lint
  image: python:3.12
  before_script:
    - pip install --upgrade pip
    - pip install flake8 flake8-quotes flake8-import-order flake8-bugbear flake8-comprehensions 
  script:
    - flake8 --max-line-length=88 --ignore=Q000,Q001,Q002,Q003 .
  only:
    - main
    - merge_requests



# Job для проверки форматирования кода с помощью Black
Black:
  stage: Black
  image: python:3.12
  before_script:
    - pip install --upgrade pip
    - pip install black==24.10.0
  script:
    - black --check .
  only:
    - main
    - merge_requests