stages:
  - linting
  - testing

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - flake8 --max-line-length=88 --ignore=Q000,Q001,Q002,Q003 .
  only:
    - main
    - merge_requests


black:
  stage: linting
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check .
  only:
    - main
    - merge_requests

django:
  stage: testing
  image: python:3.12
  before_script:
    - pip install --upgrade pip
    - pip install -r ./requirements/test.txt
  script:
    - python3 ./lyceum/manage.py test about
    - python3 ./lyceum/manage.py test catalog
    - python3 ./lyceum/manage.py test homepage
  only:
    - main
    - merge_requests
  