stages:
  - dependencies
  - black
  - test
  - flake8
  - flake8_extended

# Проверка зависимостей
check_dependencies:
  stage: dependencies
  image: python:3.12
  before_script:
    - pip install --upgrade pip
  script:
    - pip install -r requirements/prod.txt
    - pip install -r requirements/dev.txt
    - pip install -r requirements/test.txt
  only:
    - main
    - merge_requests

# Линтинг кода с помощью flake8
flake8:
  stage: flake8
  image: python:3.12
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements/dev.txt
    - pip install flake8 flake8-quotes flake8-import-order flake8-bugbear flake8-comprehensions
  script:
    - flake8 --max-line-length=88 --ignore=Q000,Q001,Q002,Q003 .  # Отключаем проверку кавычек
  only:
    - main
    - merge_requests

# Проверка Black (без изменения файлов, согласование с flake8)
black:
  stage: black
  image: python:3.12
  before_script:
    - pip install --upgrade pip
    - pip install black
  script:
    - black --check .
  only:
    - main
    - merge_requests