# Generated by Django 4.2.9 on 2025-04-02 10:47

import catalog.validators
import core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название товара",
                        max_length=150,
                        unique=True,
                        verbose_name="admin name",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Опубликован ли товар",
                        verbose_name="admin is published",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Введите уникальный слаг. Допустимы латинские буквы, цифры, '-' и '_'.",
                        max_length=200,
                        unique=True,
                        validators=[core.validators.validate_slug],
                        verbose_name="slug",
                    ),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        editable=False,
                        help_text="Автоматически нормализованное имя для уникальности.",
                        max_length=200,
                        verbose_name="нормализованное имя",
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Вес категории от 1 до 32767 (по умолчанию 100).",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="Вес должен быть не менее 1."
                            ),
                            django.core.validators.MaxValueValidator(
                                32767, message="Вес должен быть не более 32767."
                            ),
                        ],
                        verbose_name="weight",
                    ),
                ),
            ],
            options={
                "verbose_name": "admin category",
                "verbose_name_plural": "admin categories",
                "ordering": ("weight",),
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название товара",
                        max_length=150,
                        unique=True,
                        verbose_name="admin name",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Опубликован ли товар",
                        verbose_name="admin is published",
                    ),
                ),
                (
                    "text",
                    tinymce.models.HTMLField(
                        help_text="Введите текст товара, который обязательно должен содержать слово 'превосходно' или 'роскошно'.",
                        validators=[
                            catalog.validators.ValidateMustContain(
                                "Превосходно", "Роскошно"
                            )
                        ],
                        verbose_name="admin text",
                    ),
                ),
                (
                    "is_on_main",
                    models.BooleanField(
                        default=False,
                        help_text="Если True, то товар отображается на главной странице",
                        verbose_name="is_on_main",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="admin created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="admin updated at"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Выберите категорию для этого товара.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        related_query_name="item",
                        to="catalog.category",
                        verbose_name="admin category",
                    ),
                ),
            ],
            options={
                "verbose_name": "admin item",
                "verbose_name_plural": "admin items",
                "ordering": ("category__name",),
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название товара",
                        max_length=150,
                        unique=True,
                        verbose_name="admin name",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Опубликован ли товар",
                        verbose_name="admin is published",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Введите уникальный слаг. Допустимы латинские буквы, цифры, '-' и '_'.",
                        max_length=200,
                        unique=True,
                        validators=[core.validators.validate_slug],
                        verbose_name="slug",
                    ),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        editable=False,
                        help_text="Автоматически нормализованное имя для уникальности.",
                        max_length=200,
                        verbose_name="нормализованное имя",
                    ),
                ),
            ],
            options={
                "verbose_name": "admin tag",
                "verbose_name_plural": "admin tags",
                "ordering": ("slug",),
                "default_related_name": "tags",
            },
        ),
        migrations.CreateModel(
            name="ItemMainImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Будет приведено к размерам 300x300",
                        upload_to="catalog/%Y/%m/%d/",
                        verbose_name="изображение",
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_image",
                        to="catalog.item",
                        verbose_name="admin item",
                    ),
                ),
            ],
            options={
                "verbose_name": "admin main image",
                "verbose_name_plural": "admin main images",
            },
        ),
        migrations.CreateModel(
            name="ItemImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Будет приведено к размерам 300x300",
                        upload_to="catalog/%Y/%m/%d/",
                        verbose_name="изображение",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.item",
                        verbose_name="admin item",
                    ),
                ),
            ],
            options={
                "verbose_name": "admin image",
                "verbose_name_plural": "admin images",
            },
        ),
        migrations.AddField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                help_text="Выберите один или несколько тегов для этого товара.",
                related_name="items",
                related_query_name="item",
                to="catalog.tag",
                verbose_name="admin tags",
            ),
        ),
    ]
