# Generated by Django 4.2.9 on 2025-02-20 20:38

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("catalog", "0001_initial"),
        ("catalog", "0002_alter_category_options_alter_item_options_and_more"),
        (
            "catalog",
            "0003_alter_tag_options_alter_category_is_published_and_more",
        ),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название товара",
                        max_length=150,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Опубликован ли товар",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text="Введите уникальный слаг. Допустимы латинские буквы, цифры, '-' и '_'.",
                        max_length=200,
                        unique=True,
                        validators=[catalog.validators.validate_slug],
                        verbose_name="Слаг",
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Укажите вес категории (от 1 до 32767; значение по умолчанию 100).",
                        validators=[catalog.validators.validate_weight],
                        verbose_name="Вес",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название товара",
                        max_length=150,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Опубликован ли товар",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text="Введите уникальный слаг. Допустимы латинские буквы, цифры, '-' и '_'.",
                        max_length=200,
                        unique=True,
                        validators=[catalog.validators.validate_slug],
                        verbose_name="Слаг",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название товара",
                        max_length=150,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Опубликован ли товар",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Введите текст товара, который обязательно должен содержать слово 'превосходно' или 'роскошно'.",
                        validators=[
                            catalog.validators.has_prevoshodno_or_roskoshno_word
                        ],
                        verbose_name="Текст",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Выберите категорию, к которой относится товар.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        help_text="Выберите один или несколько тегов для этого товара.",
                        related_name="items",
                        to="catalog.tag",
                        verbose_name="Теги",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
