# Generated by Django 4.2.9 on 2025-02-21 12:18

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="weight",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Вес категории от 1 до 32767 (по умолчанию 100).",
                validators=[catalog.validators.validate_weight],
                verbose_name="Вес",
            ),
        ),
    ]
