# Generated by Django 4.2.9 on 2025-02-18 17:16

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Тэг", "verbose_name_plural": "Тэги"},
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.CharField(
                help_text="Введите уникальный слаг. Допустимы латинские буквы, цифры, '-' и '_'.",
                max_length=200,
                unique=True,
                validators=[catalog.validators.validate_slug],
                verbose_name="Слаг",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="weight",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Укажите вес категории (от 1 до 32767; значение по умолчанию 100).",
                validators=[catalog.validators.validate_weight],
                verbose_name="Вес",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                help_text="Выберите категорию, к которой относится товар.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                help_text="Выберите один или несколько тегов для этого товара.",
                related_name="items",
                to="catalog.tag",
                verbose_name="Теги",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                help_text="Введите текст товара, который обязательно должен содержать слово 'превосходно' или 'роскошно'.",
                validators=[catalog.validators.has_prevoshodno_or_roskoshno_word],
                verbose_name="Текст",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.CharField(
                help_text="Введите уникальный слаг. Допустимы латинские буквы, цифры, '-' и '_'.",
                max_length=200,
                unique=True,
                validators=[catalog.validators.validate_slug],
                verbose_name="Слаг",
            ),
        ),
    ]
