# Generated by Django 4.2.9 on 2025-02-21 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                help_text="Выберите категорию для этого товара.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
    ]
