# Generated by Django 4.2.9 on 2025-03-15 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_itemimages_itemmainimages_delete_itemimage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ItemMainImages",
            new_name="ItemMainImage",
        ),
    ]
