# Generated by Django 4.2.9 on 2025-02-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_item_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="normalized_name",
            field=models.CharField(
                default="",
                editable=False,
                help_text="Автоматически нормализованное имя для уникальности.",
                max_length=200,
                unique=True,
                verbose_name="Нормализованное имя",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="normalized_name",
            field=models.CharField(
                default="",
                editable=False,
                help_text="Автоматически нормализованное имя для уникальности.",
                max_length=200,
                unique=True,
                verbose_name="Нормализованное имя",
            ),
            preserve_default=False,
        ),
    ]
