# Generated by Django 4.2.9 on 2025-02-23 12:27

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_category_normalized_name_tag_normalized_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="normalized_name",
            field=models.CharField(
                editable=False,
                help_text="Автоматически нормализованное имя для уникальности.",
                max_length=150,
                unique=True,
                verbose_name="нормализованное имя",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="Введите уникальный слаг. Допустимы латинские буквы, цифры, '-' и '_'.",
                max_length=200,
                unique=True,
                validators=[catalog.validators.validate_slug],
                verbose_name="слаг",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="weight",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Вес категории от 1 до 32767 (по умолчанию 100).",
                validators=[catalog.validators.validate_weight],
                verbose_name="вес",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                help_text="Выберите категорию для этого товара.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="catalog.category",
                verbose_name="категория",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                help_text="Выберите один или несколько тегов для этого товара.",
                related_name="items",
                to="catalog.tag",
                verbose_name="теги",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                help_text="Введите текст товара, который обязательно должен содержать слово 'превосходно' или 'роскошно'.",
                validators=[
                    catalog.validators.ValidateMustContain("Превосходно", "Роскошно")
                ],
                verbose_name="текст",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="normalized_name",
            field=models.CharField(
                editable=False,
                help_text="Автоматически нормализованное имя для уникальности.",
                max_length=200,
                unique=True,
                verbose_name="нормализованное имя",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                help_text="Введите уникальный слаг. Допустимы латинские буквы, цифры, '-' и '_'.",
                max_length=200,
                unique=True,
                validators=[catalog.validators.validate_slug],
                verbose_name="слаг",
            ),
        ),
    ]
