# Generated by Django 4.2.9 on 2025-03-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_rename_itemmainimages_itemmainimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemmainimage",
            name="image",
            field=models.ImageField(
                help_text="Будет приведено к размерам 300x300",
                upload_to="catalog/%Y/%m/%d/",
                verbose_name="главное изображение",
            ),
        ),
    ]
