# Generated by Django 4.2.9 on 2025-03-18 20:45

import catalog.validators
from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_itemmainimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=tinymce.models.HTMLField(
                help_text="Введите текст товара, который обязательно должен содержать слово 'превосходно' или 'роскошно'.",
                validators=[
                    catalog.validators.ValidateMustContain("Превосходно", "Роскошно")
                ],
                verbose_name="текст",
            ),
        ),
    ]
