# Generated by Django 4.2.9 on 2025-03-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_item_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(
                default=False,
                help_text="Если True, то товар отображается на главной странице",
                verbose_name="на главной странице",
            ),
        ),
    ]
