# Generated by Django 4.2.9 on 2025-03-21 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("catalog", "0007_item_is_on_main"),
        ("catalog", "0008_alter_item_options"),
        ("catalog", "0009_alter_category_normalized_name"),
        ("catalog", "0010_alter_tag_normalized_name"),
        ("catalog", "0011_alter_item_category_alter_item_tags"),
    ]

    dependencies = [
        ("catalog", "0006_alter_item_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(
                default=False,
                help_text="Если True, то товар отображается на главной странице",
                verbose_name="на главной странице",
            ),
        ),
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ("name",),
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="normalized_name",
            field=models.CharField(
                editable=False,
                help_text="Автоматически нормализованное имя для уникальности.",
                max_length=150,
                verbose_name="нормализованное имя",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="normalized_name",
            field=models.CharField(
                editable=False,
                help_text="Автоматически нормализованное имя для уникальности.",
                max_length=200,
                verbose_name="нормализованное имя",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                help_text="Выберите категорию для этого товара.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                related_query_name="item",
                to="catalog.category",
                verbose_name="категория",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                help_text="Выберите один или несколько тегов для этого товара.",
                related_name="items",
                related_query_name="item",
                to="catalog.tag",
                verbose_name="теги",
            ),
        ),
    ]
