# Generated by Django 4.2.9 on 2025-03-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_item_is_on_main"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ("name",),
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
    ]
