# Generated by Django 4.2.9 on 2025-03-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_item_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="normalized_name",
            field=models.CharField(
                editable=False,
                help_text="Автоматически нормализованное имя для уникальности.",
                max_length=150,
                verbose_name="нормализованное имя",
            ),
        ),
    ]
