# Generated by Django 4.2.9 on 2025-03-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_category_normalized_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="normalized_name",
            field=models.CharField(
                editable=False,
                help_text="Автоматически нормализованное имя для уникальности.",
                max_length=200,
                verbose_name="нормализованное имя",
            ),
        ),
    ]
