# Generated by Django 4.2.9 on 2025-03-21 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_tag_normalized_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                help_text="Выберите категорию для этого товара.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                related_query_name="item",
                to="catalog.category",
                verbose_name="категория",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                help_text="Выберите один или несколько тегов для этого товара.",
                related_name="items",
                related_query_name="item",
                to="catalog.tag",
                verbose_name="теги",
            ),
        ),
    ]
