# Generated by Django 4.2.9 on 2025-03-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0007_item_is_on_main_squashed_0011_alter_item_category_alter_item_tags",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ("category__name",),
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
    ]
