# Generated by Django 4.2.9 on 2025-03-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ("catalog", "0012_alter_item_options"),
        ("catalog", "0013_alter_category_options_alter_tag_options"),
        ("catalog", "0014_alter_category_options_alter_tag_options"),
    ]

    dependencies = [
        (
            "catalog",
            "0007_item_is_on_main_squashed_0011_alter_item_category_alter_item_tags",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ("category__name",),
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("weight",),
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "default_related_name": "tags",
                "ordering": ("slug",),
                "verbose_name": "тег",
                "verbose_name_plural": "теги",
            },
        ),
    ]
