# Generated by Django 4.2.9 on 2025-03-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_alter_item_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("name",),
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ("name",),
                "verbose_name": "тег",
                "verbose_name_plural": "теги",
            },
        ),
    ]
