# Generated by Django 4.2.9 on 2025-03-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_alter_category_options_alter_tag_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("weight",),
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "default_related_name": "tags",
                "ordering": ("slug",),
                "verbose_name": "тег",
                "verbose_name_plural": "теги",
            },
        ),
    ]
