# Generated by Django 4.2.9 on 2025-03-29 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_alter_item_created_at_alter_item_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("weight",),
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ("category__name",),
                "verbose_name": "item",
                "verbose_name_plural": "items",
            },
        ),
        migrations.AlterModelOptions(
            name="itemimages",
            options={"verbose_name": "image", "verbose_name_plural": "images"},
        ),
        migrations.AlterModelOptions(
            name="itemmainimage",
            options={
                "verbose_name": "main image",
                "verbose_name_plural": "main images",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "default_related_name": "tags",
                "ordering": ("slug",),
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
            },
        ),
    ]
