# Generated by Django 4.2.9 on 2025-03-29 19:29

import catalog.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_alter_category_options_alter_item_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("weight",),
                "verbose_name": "admin category",
                "verbose_name_plural": "admin categories",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ("category__name",),
                "verbose_name": "admin item",
                "verbose_name_plural": "admin items",
            },
        ),
        migrations.AlterModelOptions(
            name="itemimages",
            options={
                "verbose_name": "admin image",
                "verbose_name_plural": "admin images",
            },
        ),
        migrations.AlterModelOptions(
            name="itemmainimage",
            options={
                "verbose_name": "admin main image",
                "verbose_name_plural": "admin main images",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "default_related_name": "tags",
                "ordering": ("slug",),
                "verbose_name": "admin tag",
                "verbose_name_plural": "admin tags",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Опубликован ли товар",
                verbose_name="admin is published",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Название товара",
                max_length=150,
                unique=True,
                verbose_name="admin name",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="Введите уникальный слаг. Допустимы латинские буквы, цифры, '-' и '_'.",
                max_length=200,
                unique=True,
                validators=[catalog.validators.validate_slug],
                verbose_name="slug",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="weight",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Вес категории от 1 до 32767 (по умолчанию 100).",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Вес должен быть не менее 1."
                    ),
                    django.core.validators.MaxValueValidator(
                        32767, message="Вес должен быть не более 32767."
                    ),
                ],
                verbose_name="weight",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                help_text="Выберите категорию для этого товара.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                related_query_name="item",
                to="catalog.category",
                verbose_name="admin category",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="admin created at"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(
                default=False,
                help_text="Если True, то товар отображается на главной странице",
                verbose_name="is_on_main",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Опубликован ли товар",
                verbose_name="admin is published",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(
                help_text="Название товара",
                max_length=150,
                unique=True,
                verbose_name="admin name",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                help_text="Выберите один или несколько тегов для этого товара.",
                related_name="items",
                related_query_name="item",
                to="catalog.tag",
                verbose_name="admin tags",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=tinymce.models.HTMLField(
                help_text="Введите текст товара, который обязательно должен содержать слово 'превосходно' или 'роскошно'.",
                validators=[
                    catalog.validators.ValidateMustContain("Превосходно", "Роскошно")
                ],
                verbose_name="admin text",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="admin updated at"
            ),
        ),
        migrations.AlterField(
            model_name="itemimages",
            name="image",
            field=models.ImageField(
                help_text="Будет приведено к размерам 300x300",
                upload_to="catalog/%Y/%m/%d/",
                verbose_name="admin image",
            ),
        ),
        migrations.AlterField(
            model_name="itemimages",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.item",
                verbose_name="admin item",
            ),
        ),
        migrations.AlterField(
            model_name="itemmainimage",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_image",
                to="catalog.item",
                verbose_name="admin item",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Опубликован ли товар",
                verbose_name="admin is published",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                help_text="Название товара",
                max_length=150,
                unique=True,
                verbose_name="admin name",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                help_text="Введите уникальный слаг. Допустимы латинские буквы, цифры, '-' и '_'.",
                max_length=200,
                unique=True,
                validators=[catalog.validators.validate_slug],
                verbose_name="slug",
            ),
        ),
    ]
